[package]
name = "fast_sieve_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[[bin]]
name = "test42"
path = "src/main.rs"

[dependencies]
rug = "1.15.0"
